{{- if .Values.did.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: did # Hardcoded name to unify http access to the service
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dsc.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.did.serviceType }}
  ports:
    - name: http
      port: {{ .Values.did.port }}
      targetPort: 3000
      protocol: TCP      
  selector:
    name: {{ printf "did-%s" .Values.did.type }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}