{{- if (.Values.did).enabled }}
{{- $secretKeyField := default "store-pass" .Values.did.pfx.secretKeyField }}
{{- $secretName := .Values.did.pfx.secretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dsc.labels" . | nindent 4 }}
data:
  {{ $secretKeyField }}: {{ randAlphaNum 128 | b64enc | quote }}
{{- end }}
