{{- if and (.Values.keycloak).enabled }}
{{- $keycloakSecretName := include "consumer.keycloak.secretName" . }}
{{- $keycloakSecretKey := include "consumer.keycloak.secretKey" . }}
{{- $keycloakSecret := randAlphaNum 64 | b64enc | quote }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $keycloakSecretName) }}
{{- if $existingSecret }}
{{- $keycloakSecret = index $existingSecret.data $keycloakSecretKey }}
{{- end }}

kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: {{ $keycloakSecretName }}
    namespace: {{ $.Release.Namespace | quote }}
    annotations:
        "helm.sh/resource-policy": "keep"
data:
    {{ $keycloakSecretKey }}: {{ $keycloakSecret }}
{{- end }}