routes:
# - 
#   uri: /*
#   host: fiwaredsc-consumer.local
#   methods: 
#     - GET    
#   upstream:
#     type: roundrobin
#     nodes:
#       echo-svc:8080: 1
# - 
#   uri: /*
#   host: fiwaredsc-api6dashboard.local
#   methods: 
#     - GET    
#     - POST
#     - PUT
#     - HEAD
#     - CONNECT
#     - OPTIONS
#     - PATCH
#     - DELETE
#   upstream:
#     type: roundrobin
#     nodes:
#       apisix-dashboard:80: 1
#END