apiVersion: v2
name: verifier
description: Chart holder for argo-cd

type: application
version: 0.0.1
appVersion: "4.0.0"
dependencies:
# authorization
  - name: odrl-pap
    # https://fiware.github.io/helm-charts/
    condition: odrl-pap.enabled
    version: 0.0.21
    repository: https://fiware.github.io/helm-charts/
  - name: postgresql
    condition: postgresql.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.1.5