apiVersion: v2
name: consumer
description: A Helm chart for Kubernetes to deploy Keycloak
type: application
version: 1.0.0
appVersion: "17.0.1"
dependencies:
  # - name: postgresql
  #   condition: postgresql.enabled
  #   repository: oci://registry-1.docker.io/bitnamicharts
  #   version: 13.1.5

  - name: keycloak
    condition: keycloak.enabled
    version: 24.0.1
    repository: https://charts.bitnami.com/bitnami