{{- if and (.Values.did).enabled (((.Values.did).ingress).enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "did-%s" .Values.did.type }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "did.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ (.Values.did).ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: did
                port:
                  name: http
{{- end }}
