{{- if and (.Values.mysql).enabled ((.Values.mysql).auth).existingSecret }}
{{- $secretName := .Values.mysql.auth.existingSecret }}
{{- $mysqlRootPassword := randAlphaNum 64 | b64enc | quote }}
{{- $mysqlPassword := randAlphaNum 64 | b64enc | quote }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $existingSecret }}
{{- $mysqlRootPassword = index $existingSecret.data "mysql-root-password" }}
{{- $mysqlPassword = index $existingSecret.data "mysql-password" }}
{{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
      "helm.sh/resource-policy": "keep"
data:
  mysql-root-password: {{ $mysqlRootPassword }}
  mysql-password: {{ $mysqlPassword }}
{{- end }}
