apiVersion: v2
name: trust-anchor
description: Umbrella Chart to provide a minimal trust anchor for a FIWARE Dataspace
version: 0.0.1
dependencies:
  - name: mysql
    condition: mysql.enabled
    # version: 9.4.4
    version: 11.1.10
    repository: https://charts.bitnami.com/bitnami
  - name: trusted-issuers-list
    condition: trusted-issuers-list.enabled
    version: 0.7.0
    repository: https://fiware.github.io/helm-charts