apiVersion: v2
name: verifier
description: Chart holder for argo-cd

type: application
version: 0.0.1
appVersion: "4.0.0"
dependencies:
  - name: credentials-config-service
    condition: credentials-config-service.enabled
    version: 0.1.5
    repository: https://fiware.github.io/helm-charts
  - name: mysql
    condition: mysql.enabled
    version: 9.4.4
    repository: https://charts.bitnami.com/bitnami
  - name: vcverifier
    condition: vcverifier.enabled
    version: 2.9.2
    repository: https://fiware.github.io/helm-charts
  - name: trusted-issuers-list
    condition: trusted-issuers-list.enabled
    version: 0.7.0
    repository: https://fiware.github.io/helm-charts